id: D94FDDEE5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:39:41+00:00'
last_modified: '2022-05-30T04:07:42.362780+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    ecfc:
      image_group_id: I1PD95938
      title: དགེ་སློང་གི་དང་པོའི་ལོ་དྲི་བ།
      total_pages: 1484
      order: 93
      base_file: ecfc.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
